version: '3.9'
services:
  test-repo-clone:
    image: alpine:latest
    command: sh -c "apk add --no-cache git && git clone https://github.com/ddavid-almeida/meus_repositorios.git /usr/src/app && tail -f /dev/null"
    networks:
      - traefik_public
    volumes:
      - /root/repositorios:/usr/src/app
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  traefik_public:
    external: true
