version: '3.8'

services:
  node:
    image: node:latest
    container_name: nodejs
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    command: bash -c "npm install && npm start"
